name: sc_robustness
channels:
  - conda-forge
dependencies:
  - dill
  - numpy
  - pandas
  - python-igraph=0.11.6
  - matplotlib
  - seaborn
  - dask
  - cachey
  - certifi
  - openpyxl
  - tqdm
prefix: C:\Users\Isaac\miniforge3\envs\sc_robustness
